package com.odyssey.physics;

import com.badlogic.gdx.math.Vector2;
import com.badlogic.gdx.physics.box2d.*;
import com.badlogic.gdx.utils.TimeUtils;
import com.odyssey.ShipData;

public class EnergyContactListener implements ContactListener {

    private final Vector2 velA    = new Vector2();
    private final Vector2 velB    = new Vector2();
    private final Vector2 normVec = new Vector2();

    // Sparks (◆) earned per collision type
    private static final float SPARK_INTERN_INTERN = 20f;  // multiplied by collisionEnergyMult
    private static final float SPARK_WALL          = 0.5f; // every ring/wall hit
    private static final float SPARK_GRAVITY        = 50f;  // extra on gravity well contact

    @Override
    public void beginContact(Contact contact) {
        Fixture fA = contact.getFixtureA();
        Fixture fB = contact.getFixtureB();
        if (fA.isSensor() || fB.isSensor()) return;

        Body bodyA = fA.getBody();
        Body bodyB = fB.getBody();

        boolean aIsIntern     = bodyA.getUserData() instanceof String && ((String)bodyA.getUserData()).startsWith("INTERN");
        boolean bIsIntern     = bodyB.getUserData() instanceof String && ((String)bodyB.getUserData()).startsWith("INTERN");
        boolean aIsBumper     = bodyA.getUserData() instanceof ShipData.BumperHitData;
        boolean bIsBumper     = bodyB.getUserData() instanceof ShipData.BumperHitData;
        boolean fixtureIsBump = "BUMPER".equals(fA.getUserData()) || "BUMPER".equals(fB.getUserData());
        boolean attractorHit  = fixtureIsBump && !aIsBumper && !bIsBumper; // gravity-well core, not regular bumper
        boolean bumperHit     = aIsBumper || bIsBumper || fixtureIsBump;

        ShipData sd = ShipData.get();

        if (aIsIntern && bIsIntern) {
            // Intern-intern: primary spark source
            float sparks = SPARK_INTERN_INTERN * sd.collisionEnergyMult;
            sd.addCrystals(sparks);
            queueFloatNum(contact, bodyA, bodyB, sparks, 1, sd);

            // Velocity boost to keep chaos alive
            velA.set(bodyA.getLinearVelocity());
            velB.set(bodyB.getLinearVelocity());
            normVec.set(bodyB.getPosition()).sub(bodyA.getPosition());
            if (normVec.len2() > 0.0001f) {
                normVec.nor();
                float boost = sd.internBoostStrength;
                bodyA.applyLinearImpulse(-normVec.x * boost, -normVec.y * boost,
                    bodyA.getPosition().x, bodyA.getPosition().y, true);
                bodyB.applyLinearImpulse( normVec.x * boost,  normVec.y * boost,
                    bodyB.getPosition().x, bodyB.getPosition().y, true);
            }
        } else {
            if (bumperHit) {
                float bonus     = attractorHit ? SPARK_GRAVITY : sd.bumperSparkValue;
                int   colorType = attractorHit ? 2 : 3; // 3 = bumper (gold), 2 = gravity (purple), 1 = intern (cyan)
                sd.addCrystals(bonus);
                long nowMs = TimeUtils.millis();
                if (aIsBumper) ((ShipData.BumperHitData) bodyA.getUserData()).lastHitMs = nowMs;
                if (bIsBumper) ((ShipData.BumperHitData) bodyB.getUserData()).lastHitMs = nowMs;
                queueFloatNum(contact, bodyA, bodyB, bonus, colorType, sd);
            } else {
                sd.addCrystals(SPARK_WALL);
            }
        }
        // Note: Joules are no longer generated by collisions.
        // They are earned passively by ring speed × intern count in EngineeringLabScreen.stepPhysics().
    }

    private void queueFloatNum(Contact contact, Body bA, Body bB, float value, int colorType, ShipData sd) {
        WorldManifold wm = contact.getWorldManifold();
        float cx, cy;
        if (wm.getNumberOfContactPoints() > 0) {
            cx = wm.getPoints()[0].x;
            cy = wm.getPoints()[0].y;
        } else {
            cx = (bA.getPosition().x + bB.getPosition().x) * 0.5f;
            cy = (bA.getPosition().y + bB.getPosition().y) * 0.5f;
        }
        sd.pendingContactEvents.add(new float[]{cx, cy, value, colorType});
    }

    @Override public void endContact(Contact contact) {}
    @Override public void preSolve(Contact contact, Manifold oldManifold) {}
    @Override public void postSolve(Contact contact, ContactImpulse impulse) {}
}
